name: Cloud Desktop XFCE

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Update system
        run: sudo apt update

      - name: Install desktop environment
        run: |
          sudo apt install -y \
          xfce4 xfce4-terminal \
          tigervnc-standalone-server \
          novnc websockify \
          dbus-x11 wget curl

      - name: Setup VNC
        run: |
          mkdir -p ~/.vnc
          echo "1" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          cat <<EOF > ~/.vnc/xstartup
          #!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &
          EOF

          chmod +x ~/.vnc/xstartup

          vncserver -kill :1 || true
          vncserver :1 -geometry 1600x900 -depth 24

      - name: Start noVNC
        run: |
          nohup websockify \
          --web=/usr/share/novnc \
          6080 localhost:5901 > novnc.log 2>&1 &

      - name: Install Bore
        run: |
          wget -q https://github.com/ekzhang/bore/releases/latest/download/bore-linux-amd64
          chmod +x bore-linux-amd64
          sudo mv bore-linux-amd64 /usr/local/bin/bore

      - name: Start Bore Tunnel
        run: |
          echo "Starting tunnel..."

          nohup bore local 6080 --to bore.pub > bore.log 2>&1 &
          sleep 8

          PORT=$(grep -o "bore.pub:[0-9]*" bore.log | head -n1)

          echo "================================="
          echo "noVNC URL:"
          echo "http://$PORT/vnc.html"
          echo ""
          echo "Password VNC:"
          echo "1"
          echo "================================="

      - name: Show logs
        run: |
          echo "----- Bore Log -----"
          cat bore.log
          echo "----- noVNC Log -----"
          cat novnc.log

      - name: Keep runner alive (12h)
        run: sleep 43200
