name: XFCE noVNC Ngrok

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Update system
        run: sudo apt update

      - name: Install XFCE VNC noVNC
        run: |
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server novnc websockify wget

          mkdir -p ~/.vnc
          echo "1" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          vncserver -kill :1 || true
          vncserver -geometry 1600x900 :1

          nohup websockify --web=/usr/share/novnc 6080 localhost:5901 >/dev/null 2>&1 &

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok-v3-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin

      - name: Setup Ngrok Auth
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start Ngrok Tunnel
        run: |
          nohup ngrok http 6080 > ngrok.log 2>&1 &
          sleep 10

          echo "Tunnel URL:"
          curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'https://[^"]*'

      - name: Keep runner alive
        run: sleep 21600
