name: XFCE noVNC LocalTunnel

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Update system
        run: sudo apt update

      - name: Install XFCE VNC noVNC
        run: |
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server novnc websockify curl nodejs npm

          mkdir -p ~/.vnc
          echo "1" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          cat <<EOF > ~/.vnc/xstartup
          #!/bin/bash
          xrdb \$HOME/.Xresources
          startxfce4 &
          EOF

          chmod +x ~/.vnc/xstartup

          vncserver -kill :1 || true
          vncserver -geometry 1600x900 :1

          nohup websockify --web=/usr/share/novnc 6080 localhost:5901 >/dev/null 2>&1 &

      - name: Install LocalTunnel
        run: sudo npm install -g localtunnel

      - name: Start Tunnel
        run: |
          nohup lt --port 6080 > tunnel.log 2>&1 &
          sleep 10
          echo "======================"
          echo "noVNC URL:"
          grep -o 'https://[a-zA-Z0-9.-]*\.loca.lt' tunnel.log
          echo "Password VNC: 1"
          echo "======================"

      - name: Show Tunnel Password
        run: curl https://loca.lt/mytunnelpassword

      - name: Keep runner alive
        run: sleep 21600
